# linear_svc_estimator

# VERSION : 0.1

FROM zetdata/sci-python:2.7
#FROM zetdata/ubuntu:trusty
MAINTAINER Jiaqi Guo, guojq@zetyun.com

ADD spec.json /home/run/
ADD main.py /home/run/
ADD specparser.py /home/run/
