
-- TODO : Fill your code here
DROP TABLE IF EXISTS ${OUTPUT_output};
CREATE EXTERNAL TABLE ${OUTPUT_output} (${PARAM_SCHEMA}) ROW FORMAT DELIMITED FIELDS TERMINATED BY '${PARAM_FIELD_DELIMITER}' LOCATION '${INPUT_input}';

