# datasource_to_s3

# VERSION : 0.1

FROM zetdata/ubuntu:trusty
MAINTAINER Xiaolin Zhang, zhangxl@zetyun.com

RUN pip install boto

ADD spec.json /home/run/
ADD main.py /home/run/
ADD specparser.py /home/run/
