# restapi_trigger

# VERSION : 0.1

FROM zetdata/ubuntu:trusty
MAINTAINER GuoJiaqi,guojq@zetyun.com

RUN pip install requests


ADD spec.json /home/run/
ADD main.py /home/run/
ADD specparser.py /home/run/
